module.exports = {
    "welcome": "Welcome, you can ask about city lockdown status, travel restrictions, covid cases, vaccine info, lockdown levels and more about COVID-19",
    "repromptText": "Try again, what do you like to know?",
    "national_i": ["armagh", "belfast", "londonderry", "lisburn", "newry"],
    "national_w": ["bangor", "cardiff", "newport", "st davids", "swansea"],
    "national_e": [
      "bath",
      "birmingham",
      "bradford",
      "brighton and hove",
      "bristol",
      "cambridge",
      "canterbury",
      "carlisle",
      "chester",
      "chichester",
      "coventry",
      "derby",
      "durham",
      "ely",
      "exeter",
      "gloucester",
      "hereford",
      "kingston upon hull",
      "lancaster",
      "leeds",
      "leicester",
      "lichfield",
      "lincoln",
      "city of london",
      "manchester",
      "newcastle upon tyne",
      "norwich",
      "nottingham",
      "oxford",
      "peterborough",
      "plymouth",
      "portsmouth",
      "preston",
      "ripon",
      "salford",
      "salisbury",
      "sheffield",
      "southampton",
      "st albans",
      "stoke-on-trent",
      "sunderland",
      "truro",
      "wakefield",
      "wells",
      "westminster",
      "winchester",
      "wolverhampton",
      "worcester",
      "york",
    ],
    "level1": ["dundee","80"],
    "level2": ["stirling","inverness","70"],
    "level3": [ "aberdeen","edinburgh", "liverpool","60"],
    "liverpool": {"inverness": "167.8", "stirling" : "26.2", "aberdeen": "144.9", "dundee": "80.5", "edinburgh": "46.5"}
};
